version: "3.4"
services:
  employee-ui-angular:
    container_name: employee-ui-angular
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules/
    restart: "always"
AAAAAA
# networks:
#   default:
#     external:
#       name: api_employee
